	.memblock "Sound detection"
	.print	". Sound source detection"

#if HAS_AY
	#import	"ay.inc"
#endif
#if HAS_FM
	#import	"fm.inc"
#endif

	.namespace iolib {
	.namespace detect {
	.namespace detect_sound {

detect_sound:
{
.label	sidptr	=	2

	#if io_prtstatus
		jsr primm
		.text @" Detected sound sources:\$0d\$00"
		#if HAS_TED
			jsr primm
			.text @"  TED\$0d\$00"
		#endif
	#endif
	jsr detect_sid
	#if HAS_AY
		jsr detect_ay
	#endif
	#if HAS_FM
		jsr detect_fm
	#endif
	#if HAS_MIDI
		jsr detect_midi
	#endif
	#if HAS_DAC
		jsr detect_dac
	#endif
	rts

detect_sid: {
	#if HAS_TED
		lda #<sid_solder
		ldx #>sid_solder
		sta sidptr
		stx sidptr+1
		jsr detect_sid_address
		bcc foundsid
	#if io_prtstatus
		bit debug_mode
		bpl !+
		jsr prtcr
	!:
	#endif
		lda #<sid_csory
		ldx #>sid_csory
		sta sidptr
		stx sidptr+1
		jsr detect_sid_address
	#endif
	#if !HAS_TED
		lda #<sid_base
		ldx #>sid_base
		sta sidptr
		stx sidptr+1
		jsr detect_sid_address
	#endif

	bcc foundsid
	#if io_prtstatus
		bit debug_mode
		bpl !+
		jsr prtcr
	!:	sec
	#endif
	rts

foundsid:
	lda sidptr
	ldx sidptr+1
	sta sid_1_address
	stx sid_1_address+1
	jsr detect_sid_model
	ldx #1
	bcs !+
	inx
!:	stx sid_1_model
	#if !HAS_TED
		lda #1
		sta sid_card_type
	#else
		lda #2
		sta sid_card_type
		jsr detect_2nd_sid
		jsr detect_nae
		beq nonae
		inc sid_card_type
		and #$7f
		sta sid_card_version
	nonae:
	#endif
	#if io_prtstatus
		bit debug_mode
		bpl !+
		jsr prtcr
	!:
		jsr primm
		.text @"  SID  \$00"
		lda sid_1_address
		ldx sid_1_address+1
		jsr printaddr
		lda sid_1_model
		asl
		asl
		tax
		ldy #4
	!:	lda sid_models-4,x
		jsr chrout
		inx
		dey
		bne !-

		lda sid_2_model
		beq no2ndsid
		jsr primm
		.text @"\$0d       \$00"
		lda sid_2_address
		ldx sid_2_address+1
		jsr printaddr
		lda sid_2_model
		asl
		asl
		tax
		ldy #4
	!:	lda sid_models-4,x
		jsr chrout
		inx
		dey
		bne !-
	no2ndsid:
		#if HAS_TED
			lda sid_card_type
			cmp #3
			bne noprintnae
			lda #','
			jsr chrout
			jsr prtspace
		printnae:
			ldx #'N'
			lda sid_card_version
			and #$70
			cmp #$10
			beq !+
			ldx #'C'
		!:	txa
			jsr chrout
			jsr primm
			.text @"AE v\$00"
			lda sid_card_version
			lsr
			lsr
			lsr
			lsr
			ora #'0'
			jsr chrout
			lda #'.'
			jsr chrout
			lda sid_card_version
			and #$0f
			ora #'0'
			jsr chrout
		noprintnae:
		#endif
		jsr prtcr
	#endif
	rts
	
	detect_2nd_sid: {
		lda sidptr
		cmp #<sid_solder
		bne notfound
		lda #<sid_csory
		ldx #>sid_csory
		sta sidptr
		stx sidptr+1
		jsr detect_sid_address
		bcs notfound
		
		lda #%01111111		// stop SID 2 oscillator 3
		sta sid_csory+18
		lda #%00100000		// start sawtooth on oscillator 3 on SID 1
		sta sid_solder+14
		sta sid_solder+15
		sta sid_solder+18
		ldx #64
		lda sid_csory+27
	!:	cmp sid_csory+27
		bne notfound
		dex
		bne !-
		
		lda sidptr
		ldx sidptr+1
		sta sid_2_address
		stx sid_2_address+1
		jsr detect_sid_model
		ldx #1
		bcs !+
		inx
	!:	stx sid_2_model

	notfound:
		lda #0
		sta sid_solder+18	// turn off oscillator 3 on both SIDs
		sta sid_csory+18
		rts
	}

sid_models:
	.text	"6581"
	.text	"8580"
}

#if HAS_AY
detect_ay: {
.const AY_TEST_DATA = %01011010
	lda #<digimoooz.ay
	ldx #>digimoooz.ay
	sta ay_address
	stx ay_address+1
	ldy	#15
	lda	#0
!:	sty digimoooz.ay_address
	sta digimoooz.ay_write
	dey
	bpl	!-

	ldy #1
	lda #AY_TEST_DATA
	sty digimoooz.ay_address
	sta digimoooz.ay_write

	sty digimoooz.ay_address
	lda digimoooz.ay_read
	jsr check_ay
	bcs nodigimoooz

	stx ay_model
	lda #2
	sta ay_card_type
	ldx #0
	stx ay_address_offset
	inx
	stx ay_read_offset
	stx ay_write_offset
	jmp ay_found

nodigimoooz:
	lda #<ay_base
	ldx #>ay_base
	sta ay_address
	stx ay_address+1

	ldy	#15
	lda	#0
!:	sty ay.address
	sta ay.write
	dey
	bpl	!-

	ldy #1
	lda #AY_TEST_DATA
	sty ay.address
	sta ay.write

	sty ay.address
	lda ay.read
	jsr check_ay
	bcc !+
	jmp noay

!:	stx ay_model
	lda #1
	sta ay_card_type
	ldx #0
	stx ay_read_offset
	inx
	stx ay_write_offset
	inx
	stx ay_address_offset

ay_found:
	#if io_prtstatus
		jsr primm
		.text @"  AY   \$00"
		lda ay_address
		ldx ay_address+1
		jsr printaddr
	
		ldx ay_model
		dex
		bne ym
		jsr primm
		.text @"AY-3-891x\$00"
		jmp !+
	ym:	jsr primm
		.text @"YM2149\$00"
	!:	lda #','
		jsr chrout
		lda #' '
		jsr chrout
		lda ay_card_type
		cmp #1
		bne !+
		jsr primm
		.text @"DIGIMUZ\$00"
		jmp !end_ay_card+
	!:	cmp #2
		bne !+
		jsr primm
		.text @"DigiMoooZ\$00"
	!:
	!end_ay_card:
		jsr prtcr
	#endif

	clc
	.byte BIT_ZP
noay:
	sec
	lda #0
	sta ay_address
	sta ay_address+1
	rts

check_ay: {
	#if io_prtstatus
		bit debug_mode
		bpl !+
		pha
		jsr primm
		.text @"?AY: \$00"
		lda ay_address
		ldx ay_address+1
		jsr printaddr
		lda #':'
		jsr chrout
		jsr prtspace
		pla
		pha
		jsr hexbout
		jsr prtcr
		pla
	!:
	#endif
	ldx #2
	cmp #AY_TEST_DATA
	beq ym2149
	cmp	#AY_TEST_DATA & $0f
	bne	noay
	dex
ym2149:
	clc
	rts
noay:
	sec
	rts
}
}
#endif

#if HAS_FM
detect_fm: {
.label addressptr	= sidptr
.label dataptr		= addressptr+2
.label statusptr	= dataptr+2

	sei
	ldx #<(fm.address)
	lda #>(fm.address)
	stx addressptr
	sta addressptr+1
	ldx #<(fm.data)
	stx dataptr
	sta dataptr+1
	ldx #<(fm.status)
	stx statusptr
	sta statusptr+1
	jsr detect_opl
	#if !HAS_TED
		bcc !+
		jmp notfound
	!:	lda #1
		ldx #$10
		ldy #$20
	#else
		bcs nosidekickfm
		lda #2
		ldx #1
		ldy #2
		sta fm_card_type
		stx fm_data_offset
		sty fm_status_offset
	nosidekickfm:
		ldx #<(soundx.address)
		lda #>(soundx.address)
		stx addressptr
		sta addressptr+1
		ldx #<(soundx.data)
		stx dataptr
		sta dataptr+1
		ldx #<(soundx.status)
		stx statusptr
		sta statusptr+1
		jsr detect_opl
		bcc !+
		lda fm_card_type
		bne !++
		jmp notfound
	!:	lda fm_card_type
		beq !+
		lda #4
		.byte BIT_ABS
	!:	lda #3
		ldx #1
		ldy #0
	#endif
found:
	sta fm_card_type
	stx fm_data_offset
	sty fm_status_offset
	cmp #4
	bne !+
	lda #2
	.byte BIT_ABS
!:	lda #1
	sta fm_model
	lda addressptr
	ldx addressptr+1
	sta fm_address
	stx fm_address+1
	#if io_prtstatus
		jsr primm
		.text @"  FM   \$00"
		lda fm_address
		ldx fm_address+1
		jsr printaddr
		lda fm_card_type
		cmp #4
		bne !+
		jsr primm
		.text @"OPL3, \$00"
		jmp !++
	!:	jsr primm
		.text @"OPL/OPL-II, \$00"
	!:	ldx fm_card_type
		dex
		bne !+
		jsr primm
		.text @"Snd Expander\$00"
		jmp foundend
	!:	dex
		bne !+
		jsr primm
		.text @"SideKick\$00"
		jmp foundend
	!:	dex
		bne !+
		jsr primm
		.text @"SoundX\$00"
		jmp foundend
	!:	jsr primm
		.text @"YaPE\$00"
foundend:
		jsr prtcr
	#endif
	clc
	.byte BIT_ZP
notfound:
	sec
	cli
	rts

	detect_opl: {
		#if io_prtstatus
			bit debug_mode
			bpl !+
			jsr primm
			.text @"?FM: \$00"
			lda addressptr+1
			jsr hexbout
			lda addressptr
			jsr hexbout
			lda #':'
			jsr chrout
		!:
		#endif

		ldy #0
		ldx	#4
		lda	#$60
		jsr	writefmreg
		lda	#$80
		jsr	writefmreg
		lda	(statusptr),y
		and	#$e0
		sta	fmstat1
		ldx	#2
		lda	#$ff
		jsr	writefmreg
		ldx	#4
		lda	#$21
		jsr	writefmreg
		.for	(var i=0; i<72; i++) nop
		lda	(statusptr),y
		and	#$e0
		sta	fmstat2
		ldx	#4
		lda	#$60
		jsr	writefmreg
		lda	#$80
		jsr	writefmreg

		lda	fmstat1: #0
		bne	!+

		lda	fmstat2: #0
		cmp	#$c0
		beq	found
	!:
		sec
		.byte BIT_ZP

	found:
		clc

		#if io_prtstatus
			php
			bit debug_mode
			bpl !+
			lda detect_opl.fmstat1
			jsr hexbout
			jsr prtspace
			lda detect_opl.fmstat2
			jsr hexbout
			jsr prtcr
		!:	plp
		#endif
		rts
	}

	//  3.3us after address  write: 6 NTSC double cycles, 4 C64 cycles
	// 35.0us after register write: 42 NTSC double cycles, 24 C64 cycles
	// see: https://c64.xentax.com/index.php/15-testing-ym3812-register-write-timing
	writefmreg: {
		pha
		txa
		sta	(addressptr),y
		pla	// takes 6 cycles
		sta	(dataptr),y
		.for	(var i=0; i<15; i++) nop // NOP takes 2 cycles, RTS takes 6, next JSR takes also 6 so we are safe with 15 NOPs
		rts
	}
}
#endif

#if HAS_MIDI
detect_midi: {
.label addressptr	= sidptr

	sei
	ldx #<(soundx.midi_data)
	lda #>(soundx.midi_data)
//	ldx #<(acia_base)
//	lda #>(acia_base)
	stx iolib.detect.detect_acia.addressptr
	sta iolib.detect.detect_acia.addressptr+1
	jsr iolib.detect.detect_acia.detect_acia_address
	bcs notfound

	lda #1
	sta midi_card_type
	lda addressptr
	ldx addressptr+1
	sta midi_address
	stx midi_address+1
	#if io_prtstatus
		jsr primm
		.text @"  MIDI \$00"
		lda midi_address
		ldx midi_address+1
		jsr printaddr
		ldx midi_card_type
		dex
		bne !+
		jsr primm
		.text @"SoundX\$00"
	!:	jsr prtcr
	#endif
	clc
	.byte BIT_ZP
notfound:
	sec
	cli
	rts
}
#endif

#if HAS_DAC
detect_dac: {
	#if !HAS_TED
		sec
		rts
	#endif
	#if HAS_TED
		lda sid_card_type
		cmp #3
		bne nonae
		lda sid_card_version
		sta dac_card_version
		lda #2
		sta dac_card_type	
		clc
		lda sid_1_address
		adc #$1e
		sta dac_address
		lda sid_1_address+1
		adc #0
		sta dac_address+1
		bne found
	nonae:
		lda ay_card_type
		cmp #2
		bne nodigimoooz
		lda #<digimoooz.dac
		ldx #>digimoooz.dac
		sta dac_address
		stx dac_address+1
		lda #4
		sta dac_card_type
		bne found
	nodigimoooz:
/*
		lda sid_card_type
		beq notfound
		lda sid_solder+$1f
		and sid_solder+$1f
		tax
		lda sid_csory+$1f
		and sid_csory+$1f
		stx dac1
		sta dac2
		lda dac1: #0
		cmp dac2: #0
		bne notfound
		cmp #0
		beq notfound
		lda #1
		bne found
	notfound:
*/
		sec
		rts
/*
		.byte BIT_ZP
	found:
		clc
	#if io_prtstatus
		php
		pha
		bit debug_mode
		bpl !+
		jsr primm
		.text @"?DAC: \$00"
		lda dac1
		jsr hexbout
		jsr prtspace
		lda dac2
		jsr hexbout
		jsr prtcr
	!:
		pla
		plp
	#endif
		bcc !+
		rts
	!:	
*/
found:
	#if io_prtstatus
		jsr primm
		.text @"  DAC  \$00"
		lda dac_address
		ldx dac_address+1
		jsr printaddr

		lda dac_card_type
		cmp #2
		bne !+
		jsr detect_sid.printnae
		jmp end
	!:	cmp #4
		bne !+
		jsr primm
		.text @"DigiMoooZ\$0d\$00"
		jmp end
	!:	jsr primm
		.text @"DigiBlaster\$0d\$00"
	#endif
end:
	clc
	#endif
	rts
}
#endif

// Detect SID address
//=======================================
//  In: XR: SID address low
//      YR: SID address high
// Out: AC: 0: not found $ff: found
//=======================================

detect_sid_address: {
	lda #0
	ldy #24
!:	ora (sidptr),y
	dey
	bpl !-

	cmp #0
	bne !+

	clc
	.byte BIT_ZP
!:	sec
	#if io_prtstatus
		php
		bit debug_mode
		bpl !+
		pha
		jsr primm
		.text @"?SID: \$00"
		pla
		jsr hexbout
		jsr prtspace
		tya
		jsr hexbout
	!:
		plp
	#endif
	rts
}

// Detect SID chip type
// original version from Reflex Math demo
//=======================================
detect_sid_model: {

//Set a low frequency for Oscillator
// (Voice 3) #$0200 which is somewhere
// between B-0 and C-1, according to demo

	ldy #15
	lda #$02
	sta (sidptr),y

//Set Sawtooth and Triangle waveforms for
//voice 3 and start release of ADSR

	ldy #18
	lda #%00110000
	sta (sidptr),y

//Check if output of voice 3 ever goes
//higher than $80. It's only possible on
//new SID chip (8580) and never on the
//old one (6581)

	ldy #0
	ldx #0
	sty ystore
loop2:
	ldy #27
	lda (sidptr),y
	bmi newsid
	dex
	bne loop2
	ldy ystore: #0
	dey
	sty ystore
	bne loop2
	beq oldsid
newsid:
	clc
	.byte BIT_ZP
oldsid:
	sec
	#if io_prtstatus
		php
		bit debug_mode
		bpl !+
		pha
		jsr prtspace
		pla
		jsr hexbout
	!:
		plp
	#endif
	rts
}

//=======================================
// Detect NST SIDCard
//=======================================
#if	HAS_TED
detect_nae: {
	lda #%11100000
	sta nae_control+13
	ldx #0
!:	lda nae_control+15
	cmp nae_control+15
	bne notfound
	dex
	bne !-
	and #%11100000
	cmp #%11100000
	beq notfound	// Legacy SID-Card
	lda nae_control+15
//	beq !+		// VICE :)
	clc
	.byte BIT_ZP
notfound:
	sec
	#if io_prtstatus
		php
		bit debug_mode
		bpl !+
		pha
		jsr prtspace
		pla
		pha
		jsr hexbout
		pla
	!:	plp
	#endif
	bcc !+
	lda #0
!:	rts
}
#endif

#import "detect_acia.inc"

#if io_prtstatus
	printaddr: {
		pha
//		lda #'@'
//		jsr chrout
		lda #'$'
		jsr chrout
		txa
		jsr hexbout
		pla
		jsr hexbout
		lda #':'
		jsr chrout
		jmp prtspace
	}
#endif

}
}
}
}